---

- hosts: all
  become: true
  tasks:

  - name: update repostory index
    apt:
      update_cache: yes

  - name: intstall neofetch package
    apt:
      name: neofetch
      state: latest

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
