---

- hosts: all
  become: true
  tasks:

  - name: update repostory index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: intstall neofetch package
    apt:
      name: neofetch
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repostory index
    pacman:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: intstall neofetch package
    pacman:
      name: neofetch
      state: latest
    when: ansible_distribution == "Archlinux"

  - name: install apache2 package
    pacman:
      name: apache
      state: latest
    when: ansible_distribution == "Archlinux"

  - name: add php support for apache
    pacman:
      name: php
      state: latest
    when: ansible_distribution == "Archlinux"
